name: Bug Report
description: 报告网站问题
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      placeholder: 发生了什么？
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: 浏览器
      placeholder: Chrome / Safari / Edge