name: Deploy VuePress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'pnpm'

      - name: 安装依赖
        run: pnpm install

      - name: 构建 VuePress
        run: pnpm docs:build
        working-directory: src

      - name: 上传到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/.vuepress/dist/index.html"
          target: "/www/wwwroot/mcenahle.cn/"