name: Mirror to GitLab

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/mcenahle/hope-vuepress.git
          git push gitlab --force --all
          git push gitlab --force --tags